server:
  port: ${PORT:9011}
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8000/eureka/
spring:
  application:
    name: server-file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://tianyuge_tool:tianyuge397#(&@db4free.net/tianyuge_tool_db?reconnect=true}&serverTimezone=UTC&characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    url: ${REDIS_URL:redis://tianyuge:Tianyuge397*@redis-10635.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:10635}
    database: 3