spring:
  application:
    name: eureka-server
server:
  port: 8000
  servlet:
    context-path: /
eureka:
  client:
    #由于该应用是一个注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例，不需要检索服务，所以也设置为false
    fetch-registry: false